// Generates src/styles/tokens.css from the canonical docs/design/tokens.json.
// Edit the JSON, never the generated CSS.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'docs/design/tokens.json'), 'utf8'));

const kebab = (value) => value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
const lines = [];

for (const [name, value] of Object.entries(tokens.color)) {
  lines.push(`  --color-${kebab(name)}: ${value};`);
}

lines.push(`  --font-family: ${tokens.font.family};`);
for (const [name, value] of Object.entries(tokens.font)) {
  if (typeof value !== 'object' || Array.isArray(value)) continue;
  lines.push(`  --font-${kebab(name)}-size: ${value.size}px;`);
  lines.push(`  --font-${kebab(name)}-line: ${value.lineHeight}px;`);
  lines.push(`  --font-${kebab(name)}-weight: ${value.weight};`);
}

tokens.space.forEach((value) => lines.push(`  --space-${value}: ${value}px;`));
for (const [name, value] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${kebab(name)}: ${value}px;`);
}
for (const [name, value] of Object.entries(tokens.layout)) {
  lines.push(`  --layout-${kebab(name)}: ${value}px;`);
}
for (const [name, value] of Object.entries(tokens.motionMs)) {
  lines.push(`  --motion-${kebab(name)}: ${value}ms;`);
}
lines.push(`  --focus-width: ${tokens.focus.width}px;`);
lines.push(`  --focus-offset: ${tokens.focus.offset}px;`);
for (const [name, value] of Object.entries(tokens.shadow)) {
  lines.push(`  --shadow-${kebab(name)}: ${value};`);
}

const css = `/* Generated by scripts/generate-tokens.mjs from docs/design/tokens.json v${tokens.version}. Do not edit. */\n:root {\n${lines.join('\n')}\n}\n`;

mkdirSync(join(root, 'src/styles'), { recursive: true });
writeFileSync(join(root, 'src/styles/tokens.css'), css);
console.log(`Wrote src/styles/tokens.css from tokens.json v${tokens.version}`);
